# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
      
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t react-calculator .

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1 
      with:
        registry: acramdev.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t acramdev.azurecr.io/react-calculator:${{ github.sha }} .
        docker push acramdev.azurecr.io/react-calculator:${{ github.sha }}

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Deploy to Azure Container Instances
    #   uses: azure/aci-deploy@v1
    #   with:
    #     resource-group: CaluculatorAppRG
    #     dns-name-label: react-caluculator
    #     image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/react-calculator:${{ github.sha }}
    #     registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
    #     registry-username: ${{ secrets.REGISTRY_USERNAME }}
    #     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
    #     name: react-caluculator
    #     location: 'japaneast'
